### PR TITLE
Sqrt

### PR DESCRIPTION
**Pull request by mjibson**
First 4 commits are from the nan branch (no need to review those).

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/apd/36)

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
Reviewed 1 of 1 files at r5.
Review status: 1 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[context.go, line 547 at r5](https://reviewable.io:443/reviews/cockroachdb/apd/36#-KfT3HQRh1dBxtPoxhkL:-KfT3HQRh1dBxtPoxhkM:b6to8n9) ([raw file](https://github.com/cockroachdb/apd/blob/d15f86b37cc8ba1fe81553ba56c8289c47a80d24/context.go#L547)):*
> ```Go
> 	}
> 
> 	f := new(Decimal).Set(x)
> ```

I take it you're okay with these variables remaining uncommented?

---

*[context.go, line 554 at r5](https://reviewable.io:443/reviews/cockroachdb/apd/36#-KfT3mjjDIJj1kJgLDAA:-KfT3mjkAAvS07bVas9b:bbct15r) ([raw file](https://github.com/cockroachdb/apd/blob/d15f86b37cc8ba1fe81553ba56c8289c47a80d24/context.go#L554)):*
> ```Go
> 	nc := c.WithPrecision(workp)
> 	nc.Rounding = RoundHalfEven
> 	ed := MakeErrDecimal(nc)
> ```

Would appreciate a comment here saying `ed` is the first guess, set based on what `e` is (it's not clear to me at all what `e%2==0` means w.r.t. `x`)

---

*[context.go, line 558 at r5](https://reviewable.io:443/reviews/cockroachdb/apd/36#-KfT3eUGZEFNzvZja0Aw:-KfT3eUGZEFNzvZja0Ax:b-k0ji65) ([raw file](https://github.com/cockroachdb/apd/blob/d15f86b37cc8ba1fe81553ba56c8289c47a80d24/context.go#L558)):*
> ```Go
> 		approx.SetCoefficient(819).SetExponent(-3)
> 		ed.Mul(approx, approx, f)
> 		ed.Add(approx, approx, New(259, -3))
> ```

Would appreciate a comment here saying `ed = .819 + f*.259` (and similarly in the else branch).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/36)*

**Comment by arjunravinarayan** [comment]
Sorry, I didn't see your responses on my PR until now, hold off on responding until I reconcile the two states.

---

Review status: 1 of 8 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/36#-:-KfT54Rxe2yBUkZHgPM3:b1wrzl0)*

**Comment by arjunravinarayan** [comment]
:lgtm:

---

Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[context.go, line 554 at r5](https://reviewable.io:443/reviews/cockroachdb/apd/36#-KfT3mjjDIJj1kJgLDAA:-KfT7ITattQKUUWDu9GU:bf72lae) ([raw file](https://github.com/cockroachdb/apd/blob/d15f86b37cc8ba1fe81553ba56c8289c47a80d24/context.go#L554)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Would appreciate a comment here saying `ed` is the first guess, set based on what `e` is (it's not clear to me at all what `e%2==0` means w.r.t. `x`)
</blockquote></details>

This one I still would like.

---

*[context.go, line 558 at r5](https://reviewable.io:443/reviews/cockroachdb/apd/36#-KfT3eUGZEFNzvZja0Aw:-KfT7CxrN9lEFHx2N_pW:b4out01) ([raw file](https://github.com/cockroachdb/apd/blob/d15f86b37cc8ba1fe81553ba56c8289c47a80d24/context.go#L558)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Would appreciate a comment here saying `ed = .819 + f*.259` (and similarly in the else branch).
</blockquote></details>

This one I withdraw to stay consistent with your "read the paper!" style choice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/36#-:-KfT77CGd-3kmx6HQTZ_:bnfp4nl)*

**Comment by mjibson** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[context.go, line 554 at r5](https://reviewable.io:443/reviews/cockroachdb/apd/36#-KfT3mjjDIJj1kJgLDAA:-Kfgps5tUiy1wFcZarJe:b-r9z37u) ([raw file](https://github.com/cockroachdb/apd/blob/d15f86b37cc8ba1fe81553ba56c8289c47a80d24/context.go#L554)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

This one I still would like.
</blockquote></details>

Done. Better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/36)*

**Comment by arjunravinarayan** [comment]
LGTM. Ship it!

---

Reviewed 1 of 1 files at r6.
Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[context.go, line 554 at r5](https://reviewable.io:443/reviews/cockroachdb/apd/36#-KfT3mjjDIJj1kJgLDAA:-KfgzFhUvgRSacBxKSaB:b-wtkc5u) ([raw file](https://github.com/cockroachdb/apd/blob/d15f86b37cc8ba1fe81553ba56c8289c47a80d24/context.go#L554)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Done. Better?
</blockquote></details>

Yes, thank you!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/36#-:-KfgzMLGZLepxUqTIk1u:b-t59ydf)*

**Pull request merged**
