### PR TITLE
allow negatives in cbrt

### LINKED ISSUE #38: Support negative numbers in cbrt

### PR DESCRIPTION
**Pull request by mjibson**
Fixes #38

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/apd/41)

### CODE REVIEW

**Comment by eisenstatdavid** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[context.go, line 458 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/41#-KfmB8clA13tmFTHZgsU:-KfmB8clA13tmFTHZgsV:b7icaat) ([raw file](https://github.com/cockroachdb/apd/blob/9f1dd2662a76bbee782583aed81d81587b8815d0/context.go#L458)):*
> ```Go
> 	switch x.Sign() {
> 	case -1:
> 		if !allowNegative {
> ```

How about `factor % 2 == 0` and omit the `allowNegative` argument (since this is the necessary and sufficient condition for the root to be defined)?

---

*[context.go, line 582 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/41#-KfmBXyryv9h2T4YvSVL:-KfmBXyryv9h2T4YvSVM:b-sb4h0g) ([raw file](https://github.com/cockroachdb/apd/blob/9f1dd2662a76bbee782583aed81d81587b8815d0/context.go#L582)):*
> ```Go
> 	if x.Negative {
> 		ax = new(Decimal).Set(x)
> 		ax.Negative = false
> ```

How about `ax = new(Decimal).Abs(x)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/41)*

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[context.go, line 458 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/41#-KfmB8clA13tmFTHZgsU:-KfmVu4npw81PPrWdLaH:b-896fix) ([raw file](https://github.com/cockroachdb/apd/blob/9f1dd2662a76bbee782583aed81d81587b8815d0/context.go#L458)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

How about `factor % 2 == 0` and omit the `allowNegative` argument (since this is the necessary and sufficient condition for the root to be defined)?
</blockquote></details>

Done.

---

*[context.go, line 582 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/41#-KfmBXyryv9h2T4YvSVL:-KfmVaMdFR3zvON5Rgkh:b-9knb87) ([raw file](https://github.com/cockroachdb/apd/blob/9f1dd2662a76bbee782583aed81d81587b8815d0/context.go#L582)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

How about `ax = new(Decimal).Abs(x)`?
</blockquote></details>

Because that forces an allocation, and we'd like to avoid that if possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/41)*

**Comment by eisenstatdavid** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[context.go, line 582 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/41#-KfmBXyryv9h2T4YvSVL:-KfmWC2QvpMl2GOFyd5K:bn3uooz) ([raw file](https://github.com/cockroachdb/apd/blob/9f1dd2662a76bbee782583aed81d81587b8815d0/context.go#L582)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Because that forces an allocation, and we'd like to avoid that if possible.
</blockquote></details>

I meant only replacing this line and the one above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/41)*

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[context.go, line 582 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/41#-KfmBXyryv9h2T4YvSVL:-KfmZj2ku-FUs9LmM5ZR:bqrsyj2) ([raw file](https://github.com/cockroachdb/apd/blob/9f1dd2662a76bbee782583aed81d81587b8815d0/context.go#L582)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

I meant only replacing this line and the one above.
</blockquote></details>

Ah. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/41)*

**Comment by eisenstatdavid** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/41#-:-KfmZzu9XmkYokRSxH25:bnfp4nl)*

**Pull request merged**
