### PR TITLE
improvements for Ln

### PR DESCRIPTION
**Pull request by RaduBerinde**
Improving the Ln implementation by scaling to range [0.1, 1) and using Math.log
for an initial estimate. Special casing for numbers close to 1 for which
scaling would require too much precision.

Also improving the precision calculation in Log10, and replacing the division
by `ln(10)` to a multiplication (by adding `1/ln(10)` constant).

Benchmarks below (about the cases that are slower: these are high-precision
cases where I believe we weren't using enough internal precision - we don't
have tests with high precisions).

```
Ln/P2/S-100/D2-24       631µs ± 1%   129µs ± 1%   -79.52%  (p=0.029 n=4+4)
Ln/P2/S-10/D2-24        322µs ± 1%   114µs ± 1%   -64.71%  (p=0.029 n=4+4)
Ln/P2/S-2/D2-24         315µs ± 1%   124µs ± 1%   -60.65%  (p=0.029 n=4+4)
Ln/P2/S2/D2-24          313µs ± 1%   111µs ± 1%   -64.44%  (p=0.029 n=4+4)
Ln/P2/S10/D2-24         372µs ± 3%   121µs ± 2%   -67.60%  (p=0.029 n=4+4)
Ln/P2/S100/D2-24        691µs ± 2%   128µs ± 2%   -81.53%  (p=0.029 n=4+4)
Ln/P10/S-100/D2-24      897µs ± 2%   284µs ± 1%   -68.29%  (p=0.029 n=4+4)
Ln/P10/S-100/D10-24     886µs ± 2%   597µs ± 1%   -32.69%  (p=0.029 n=4+4)
Ln/P10/S-10/D2-24       604µs ± 1%   284µs ± 2%   -53.00%  (p=0.029 n=4+4)
Ln/P10/S-10/D10-24      609µs ± 2%   561µs ± 1%    -7.85%  (p=0.029 n=4+4)
Ln/P10/S-2/D2-24        564µs ± 3%   313µs ± 0%   -44.58%  (p=0.029 n=4+4)
Ln/P10/S-2/D10-24       640µs ± 6%   571µs ± 1%   -10.79%  (p=0.029 n=4+4)
Ln/P10/S2/D2-24         538µs ± 1%   301µs ± 1%   -43.96%  (p=0.029 n=4+4)
Ln/P10/S2/D10-24        569µs ± 3%   587µs ± 2%      ~     (p=0.114 n=4+4)
Ln/P10/S10/D2-24        576µs ± 4%   300µs ± 3%   -47.94%  (p=0.029 n=4+4)
Ln/P10/S10/D10-24       604µs ± 4%   623µs ± 2%      ~     (p=0.200 n=4+4)
Ln/P10/S100/D2-24       918µs ± 2%   286µs ± 2%   -68.84%  (p=0.029 n=4+4)
Ln/P10/S100/D10-24      927µs ± 3%   589µs ± 2%   -36.41%  (p=0.029 n=4+4)
Ln/P100/S-100/D2-24    36.8ms ± 2%  19.0ms ± 1%   -48.18%  (p=0.029 n=4+4)
Ln/P100/S-100/D10-24   35.0ms ± 1%  20.2ms ± 3%   -42.19%  (p=0.029 n=4+4)
Ln/P100/S-100/D100-24  36.2ms ± 1%  78.0ms ± 1%  +115.44%  (p=0.029 n=4+4)
Ln/P100/S-10/D2-24     33.5ms ± 2%  17.2ms ± 2%   -48.65%  (p=0.029 n=4+4)
Ln/P100/S-10/D10-24    35.1ms ± 2%  21.1ms ± 1%   -39.96%  (p=0.029 n=4+4)
Ln/P100/S-10/D100-24   34.9ms ± 3%  71.4ms ± 1%  +104.93%  (p=0.029 n=4+4)
Ln/P100/S-2/D2-24      33.8ms ± 1%  19.3ms ± 7%   -42.98%  (p=0.029 n=4+4)
Ln/P100/S-2/D10-24     34.4ms ± 1%  22.1ms ± 3%   -35.66%  (p=0.029 n=4+4)
Ln/P100/S-2/D100-24    34.8ms ± 1%  74.0ms ± 0%  +112.48%  (p=0.029 n=4+4)
Ln/P100/S2/D2-24       30.8ms ± 2%  18.4ms ± 2%   -40.25%  (p=0.029 n=4+4)
Ln/P100/S2/D10-24      34.6ms ± 1%  22.2ms ± 2%   -35.91%  (p=0.029 n=4+4)
Ln/P100/S2/D100-24     35.7ms ± 1%  78.7ms ± 2%  +120.44%  (p=0.029 n=4+4)
Ln/P100/S10/D2-24      34.3ms ± 1%  18.7ms ± 1%   -45.57%  (p=0.029 n=4+4)
Ln/P100/S10/D10-24     32.2ms ± 1%  21.9ms ± 4%   -32.03%  (p=0.029 n=4+4)
Ln/P100/S10/D100-24    32.8ms ± 1%  82.5ms ± 2%  +151.47%  (p=0.029 n=4+4)
Ln/P100/S100/D2-24     34.7ms ± 1%  18.9ms ± 1%   -45.52%  (p=0.029 n=4+4)
Ln/P100/S100/D10-24    34.0ms ± 2%  22.3ms ± 2%   -34.31%  (p=0.029 n=4+4)
Ln/P100/S100/D100-24   34.8ms ± 1%  98.0ms ± 1%  +181.17%  (p=0.029 n=4+4)
```

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/apd/12)

### CODE REVIEW

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[const.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/12#-KcH-Eedl2YGUYyBO24I:-KcH-EeeTlAyGa9VtCdT:bg6rh26) ([raw file](https://github.com/cockroachdb/apd/blob/f3d997718f79320cd56e234742a0022ae17534d7/const.go#L40)):*
> ```Go
> 
> 	decimalE = makeConstWithPrecision(strE)
> 	// ln(2)
> ```

`ln(10)`?

---

*[const.go, line 43 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/12#-KcH-JUaeY17ws2HsnuJ:-KcH-JUaeY17ws2HsnuK:b-590r3u) ([raw file](https://github.com/cockroachdb/apd/blob/f3d997718f79320cd56e234742a0022ae17534d7/const.go#L43)):*
> ```Go
> 	decimalLog10 = makeConstWithPrecision(strLog10)
> 	// 1/ln(10)
> 	decimalInvLog10 = makeConstWithPrecision(strInvLog10)
> ```

maybe we should just rename these strings to Ln: `strLn10`, etc. They were this way because I copied them from the cockroach code.

---

*[const.go, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/12#-KcH07khU28bsyq8TMzg:-KcH07kiX_cvWx2ZXFuH:b16e069) ([raw file](https://github.com/cockroachdb/apd/blob/f3d997718f79320cd56e234742a0022ae17534d7/const.go#L45)):*
> ```Go
> 	decimalInvLog10 = makeConstWithPrecision(strInvLog10)
> 	// ln(2)
> 	decimalLog2 = makeConstWithPrecision(strLog2)
> ```

Is this used anymore? We should remove it if not since makeConstWithPrecision does some work during init that we could avoid.

---

*[context.go, line 516 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/12#-KcHKMq_eF-21FBtBKhN:-KcHKMqalm9Q-RZ0pHUs:btx67u9) ([raw file](https://github.com/cockroachdb/apd/blob/f3d997718f79320cd56e234742a0022ae17534d7/context.go#L516)):*
> ```Go
> 		p += p
> 	}
> 	p += 2
> ```

Do we still need this?

---

*[context.go, line 573 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/12#-KcHMaUAzf7UysQjDMMN:-KcHMaUBsFhbAWAYayty:b-jf8i9s) ([raw file](https://github.com/cockroachdb/apd/blob/f3d997718f79320cd56e234742a0022ae17534d7/context.go#L573)):*
> ```Go
> 		if err != nil {
> 			// We know that z is in a reasonable range; no errors should happen during conversion.
> 			panic(err)
> ```

Although I agree with the analysis that this shouldn't be possible, since this function can already return an error, I think it's safer to do return instead of panic. Same for below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/12#-:-KcHSExQZ98zhF-3XJEe:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[context.go, line 516 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/12#-KcHKMq_eF-21FBtBKhN:-KcIVHmiSfUjlTDdwMu0:b-dzgqyn) ([raw file](https://github.com/cockroachdb/apd/blob/f3d997718f79320cd56e234742a0022ae17534d7/context.go#L516)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Do we still need this?
</blockquote></details>

I am reconsidering this; I will work on it a bit more.

I think we only need this double precision when `z` is close to 1, because that is when the scale of `e^a` (and `z`) and that of `a` (and `ln(z)`) differ by p, e.g. z=1.00001 vs ln(z)=~0.00001. 

But for these cases, the Taylor series for `ln(1+x)` should be much better as the terms are powers of `x` which decrease rapidly for small `x`.

I will experiment with this, and see where we have a good cut-off performance-wise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/12)*

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[context.go, line 516 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/12#-KcHKMq_eF-21FBtBKhN:-KcJTi4zxPGn_mKYRxL4:b-a6qz3x) ([raw file](https://github.com/cockroachdb/apd/blob/f3d997718f79320cd56e234742a0022ae17534d7/context.go#L516)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I am reconsidering this; I will work on it a bit more.

I think we only need this double precision when `z` is close to 1, because that is when the scale of `e^a` (and `z`) and that of `a` (and `ln(z)`) differ by p, e.g. z=1.00001 vs ln(z)=~0.00001. 

But for these cases, the Taylor series for `ln(1+x)` should be much better as the terms are powers of `x` which decrease rapidly for small `x`.

I will experiment with this, and see where we have a good cut-off performance-wise.
</blockquote></details>

I wasn't talking about doubling the precision, just adding `2` to p. No need to do more work here for this commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/12)*

**Comment by RaduBerinde** [comment]
*[context.go, line 516 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/12#-KcHKMq_eF-21FBtBKhN:-KcJW9hplCVNyYtNMLZk:bccdu8e) ([raw file](https://github.com/cockroachdb/apd/blob/f3d997718f79320cd56e234742a0022ae17534d7/context.go#L516)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I wasn't talking about doubling the precision, just adding `2` to p. No need to do more work here for this commit.
</blockquote></details>

I know, but the doubling of precision was bothering me anyway. The `+2` is there because the calculated precision applies to one iteration, but with multiple iterations the errors add up so we add a couple extra digits to compensate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/12)*

**Comment by RaduBerinde** [comment]
Updated. Added a different method (power series) for values close to 1, and with this I was able to keep the precision down. The benchmarks look much better now.

All these tests are fantastic!  I tried a bunch of variants that turned out to have precision issues.


```
name                   old time/op  new time/op  delta
Ln/P2/S-100/D2-24       665µs ± 2%   104µs ± 1%  -84.30%  (p=0.029 n=4+4)
Ln/P2/S-10/D2-24        338µs ± 1%    79µs ± 1%  -76.55%  (p=0.029 n=4+4)
Ln/P2/S-2/D2-24         334µs ± 2%    92µs ± 2%  -72.32%  (p=0.029 n=4+4)
Ln/P2/S2/D2-24          338µs ± 5%    83µs ± 3%  -75.53%  (p=0.029 n=4+4)
Ln/P2/S10/D2-24         383µs ± 2%    86µs ± 1%  -77.59%  (p=0.029 n=4+4)
Ln/P2/S100/D2-24        709µs ± 2%   101µs ± 4%  -85.68%  (p=0.029 n=4+4)
Ln/P10/S-100/D2-24      962µs ±12%   234µs ± 0%  -75.73%  (p=0.029 n=4+4)
Ln/P10/S-100/D10-24     923µs ± 1%   264µs ± 0%  -71.41%  (p=0.029 n=4+4)
Ln/P10/S-10/D2-24       636µs ± 2%   240µs ± 1%  -62.28%  (p=0.029 n=4+4)
Ln/P10/S-10/D10-24      624µs ± 2%   241µs ± 2%  -61.39%  (p=0.029 n=4+4)
Ln/P10/S-2/D2-24        581µs ± 2%   266µs ± 3%  -54.16%  (p=0.029 n=4+4)
Ln/P10/S-2/D10-24       639µs ± 3%   231µs ± 2%  -63.88%  (p=0.029 n=4+4)
Ln/P10/S2/D2-24         556µs ± 3%   254µs ± 2%  -54.34%  (p=0.029 n=4+4)
Ln/P10/S2/D10-24        601µs ± 6%   233µs ± 1%  -61.19%  (p=0.029 n=4+4)
Ln/P10/S10/D2-24        614µs ± 8%   239µs ± 2%  -61.12%  (p=0.029 n=4+4)
Ln/P10/S10/D10-24       618µs ± 3%   272µs ± 0%  -56.03%  (p=0.029 n=4+4)
Ln/P10/S100/D2-24       952µs ± 1%   231µs ± 6%  -75.75%  (p=0.029 n=4+4)
Ln/P10/S100/D10-24      942µs ± 1%   254µs ± 2%  -73.05%  (p=0.029 n=4+4)
Ln/P100/S-100/D2-24    37.4ms ± 0%  18.8ms ± 6%  -49.61%  (p=0.029 n=4+4)
Ln/P100/S-100/D10-24   36.5ms ± 1%  16.2ms ± 5%  -55.55%  (p=0.029 n=4+4)
Ln/P100/S-100/D100-24  39.0ms ± 3%  17.1ms ± 1%  -56.04%  (p=0.029 n=4+4)
Ln/P100/S-10/D2-24     34.9ms ± 2%  15.6ms ± 1%  -55.46%  (p=0.029 n=4+4)
Ln/P100/S-10/D10-24    37.5ms ±10%  16.5ms ± 5%  -56.06%  (p=0.029 n=4+4)
Ln/P100/S-10/D100-24   34.8ms ± 1%  16.9ms ± 3%  -51.29%  (p=0.029 n=4+4)
Ln/P100/S-2/D2-24      35.3ms ± 4%  18.4ms ± 2%  -47.77%  (p=0.029 n=4+4)
Ln/P100/S-2/D10-24     35.3ms ± 1%  18.0ms ± 1%  -49.18%  (p=0.029 n=4+4)
Ln/P100/S-2/D100-24    37.5ms ± 2%  18.2ms ±15%  -51.46%  (p=0.029 n=4+4)
Ln/P100/S2/D2-24       32.4ms ± 1%  17.7ms ± 1%  -45.48%  (p=0.029 n=4+4)
Ln/P100/S2/D10-24      36.8ms ± 2%  20.1ms ± 8%  -45.42%  (p=0.029 n=4+4)
Ln/P100/S2/D100-24     37.6ms ± 4%  17.1ms ± 3%  -54.50%  (p=0.029 n=4+4)
Ln/P100/S10/D2-24      36.2ms ± 2%  18.8ms ± 2%  -48.02%  (p=0.029 n=4+4)
Ln/P100/S10/D10-24     33.8ms ± 1%  18.0ms ± 1%  -46.65%  (p=0.029 n=4+4)
Ln/P100/S10/D100-24    34.8ms ± 2%  16.1ms ± 1%  -53.75%  (p=0.029 n=4+4)
Ln/P100/S100/D2-24     36.8ms ± 1%  18.5ms ± 4%  -49.73%  (p=0.029 n=4+4)
Ln/P100/S100/D10-24    36.4ms ± 2%  18.7ms ± 1%  -48.65%  (p=0.029 n=4+4)
Ln/P100/S100/D100-24   37.5ms ± 7%  20.4ms ± 4%  -45.77%  (p=0.029 n=4+4)
```

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[const.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/12#-KcH-Eedl2YGUYyBO24I:-KcK0FWF5-nF5Jen4jMY:b-896fix) ([raw file](https://github.com/cockroachdb/apd/blob/f3d997718f79320cd56e234742a0022ae17534d7/const.go#L40)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

`ln(10)`?
</blockquote></details>

Done.

---

*[const.go, line 43 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/12#-KcH-JUaeY17ws2HsnuJ:-KcK0FkbEctE995sfX33:b-896fix) ([raw file](https://github.com/cockroachdb/apd/blob/f3d997718f79320cd56e234742a0022ae17534d7/const.go#L43)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

maybe we should just rename these strings to Ln: `strLn10`, etc. They were this way because I copied them from the cockroach code.
</blockquote></details>

Done.

---

*[const.go, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/12#-KcH07khU28bsyq8TMzg:-KcK0G-5WKxflo4ORzL2:b-896fix) ([raw file](https://github.com/cockroachdb/apd/blob/f3d997718f79320cd56e234742a0022ae17534d7/const.go#L45)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Is this used anymore? We should remove it if not since makeConstWithPrecision does some work during init that we could avoid.
</blockquote></details>

Done.

---

*[context.go, line 573 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/12#-KcHMaUAzf7UysQjDMMN:-KcK0Pb3UEPAm9XDFwQL:b-896fix) ([raw file](https://github.com/cockroachdb/apd/blob/f3d997718f79320cd56e234742a0022ae17534d7/context.go#L573)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Although I agree with the analysis that this shouldn't be possible, since this function can already return an error, I think it's safer to do return instead of panic. Same for below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/12#-:-KcK0kxcnOf7W081AlJ-:bx0dgge)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/12#-:-KcK5Lff1IYPsZDqSWgh:bnfp4nl)*

**Pull request merged**
