### PR TITLE
Add negative field to decimal

### PR DESCRIPTION
**Pull request by mjibson**
For -0 support.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/apd/29)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[context.go, line 97 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/29#-KerhsOw7jnGiO2fDXOd:-KerhsOxVHl-OHV8yZsi:b4ez1v1) ([raw file](https://github.com/cockroachdb/apd/blob/81ff665965ffbc37f95bf8190aea354799e6a529/context.go#L97)):*
> ```Go
> 	xn := x.Negative
> 	yn := y.Negative
> 	ax := new(Decimal).Abs(x)
> ```

Can't we avoid one or both of these when `x` or `y` are positive?

---

*[context.go, line 103 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/29#-KermMJBwJIJFXsK1ItR:-KermMJCWZPDxeNWAvl0:b-xx48gy) ([raw file](https://github.com/cockroachdb/apd/blob/81ff665965ffbc37f95bf8190aea354799e6a529/context.go#L103)):*
> ```Go
> 	}
> 	subtract = xn != yn
> 	if a.Cmp(b) < 0 {
> ```

This can be moved into the `subtract` branch. Also, can we avoid it all together by taking the absolute value right after the `Sub`?

---

*[context.go, line 112 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/29#-Kerj-CBQkQrvDdwzY2A:-Kerj-CBQkQrvDdwzY2B:b-g2lxfs) ([raw file](https://github.com/cockroachdb/apd/blob/81ff665965ffbc37f95bf8190aea354799e6a529/context.go#L112)):*
> ```Go
> 	}
> 	d.Exponent = s
> 	if d.Sign() != 0 {
> ```

What do you think about adding a:

```
func (d *Decimal) Zero() bool {
    return d.Sign() == 0
}
```
method? Looking at the comparison always forces me to think twice about code that could be a lot easier to read.

---

*[context.go, line 124 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/29#-Keris7m4vvdQsYajfTR:-Keris7m4vvdQsYajfTS:b-pxkh73) ([raw file](https://github.com/cockroachdb/apd/blob/81ff665965ffbc37f95bf8190aea354799e6a529/context.go#L124)):*
> ```Go
> 			d.Negative = false
> 		}
> 		// TODO(mjibson): this is in the spec, do we need it?
> ```

are there `decTest`s for it?

---

*[decimal.go, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/29#-Kerket6yaPQYaDBXfdZ:-Kerket6yaPQYaDBXfd_:b-ah8baa) ([raw file](https://github.com/cockroachdb/apd/blob/81ff665965ffbc37f95bf8190aea354799e6a529/decimal.go#L34)):*
> ```Go
> type Decimal struct {
> 	Negative bool
> 	Coeff    big.Int
> ```

It's too bad we now have a wasted negative flag in the `big.Int`. Could you add to the commit message why that flag was not possible to use for this use case?

---

*[decimal.go, line 202 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/29#-KerlS4Ud1xHh5q7B_cy:-KerlS4Ud1xHh5q7B_cz:bed6jqe) ([raw file](https://github.com/cockroachdb/apd/blob/81ff665965ffbc37f95bf8190aea354799e6a529/decimal.go#L202)):*
> ```Go
> func (d *Decimal) SetCoefficient(x int64) *Decimal {
> 	d.Coeff.SetInt64(x)
> 	d.Negative = x < 0
> ```

nit: move this up one line

---

*[decimal.go, line 365 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/29#-KerlZPA_zVLR7pTJixS:-KerlZPA_zVLR7pTJixT:b-tgjovg) ([raw file](https://github.com/cockroachdb/apd/blob/81ff665965ffbc37f95bf8190aea354799e6a529/decimal.go#L365)):*
> ```Go
> }
> 
> func (d *Decimal) getBig() *big.Int {
> ```

This name implies that we're getting a reference to the `Decimal`'s `big.Int`. Instead, we're getting a deep copy. I'd either change the name to make this more clear or add a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/29)*

**Comment by mjibson** [comment]
Review status: 2 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[context.go, line 97 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/29#-KerhsOw7jnGiO2fDXOd:-Kew8RvReYyn0sdrlpmt:b-896fix) ([raw file](https://github.com/cockroachdb/apd/blob/81ff665965ffbc37f95bf8190aea354799e6a529/context.go#L97)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can't we avoid one or both of these when `x` or `y` are positive?
</blockquote></details>

Done.

---

*[context.go, line 103 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/29#-KermMJBwJIJFXsK1ItR:-Kew9ViXTaWai6zyizMj:b-896fix) ([raw file](https://github.com/cockroachdb/apd/blob/81ff665965ffbc37f95bf8190aea354799e6a529/context.go#L103)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This can be moved into the `subtract` branch. Also, can we avoid it all together by taking the absolute value right after the `Sub`?
</blockquote></details>

Done.

---

*[context.go, line 112 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/29#-Kerj-CBQkQrvDdwzY2A:-Kew8rL-DE_-QpW1Otzk:b-896fix) ([raw file](https://github.com/cockroachdb/apd/blob/81ff665965ffbc37f95bf8190aea354799e6a529/context.go#L112)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What do you think about adding a:

```
func (d *Decimal) Zero() bool {
    return d.Sign() == 0
}
```
method? Looking at the comparison always forces me to think twice about code that could be a lot easier to read.
</blockquote></details>

Done.

---

*[context.go, line 124 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/29#-Keris7m4vvdQsYajfTR:-Kew9Y_jFGDiHzPY0WoQ:b-zc9ls7) ([raw file](https://github.com/cockroachdb/apd/blob/81ff665965ffbc37f95bf8190aea354799e6a529/context.go#L124)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

are there `decTest`s for it?
</blockquote></details>

If there are we pass them. Until I can find a failing decTest I'm inclined to leave it as is because it'd require a medium-ish change to the rounding stuff since you can't compare function pointers for equality in go.

---

*[decimal.go, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/29#-Kerket6yaPQYaDBXfdZ:-Kew9lm0bgOV3Asm0TJc:b-896fix) ([raw file](https://github.com/cockroachdb/apd/blob/81ff665965ffbc37f95bf8190aea354799e6a529/decimal.go#L34)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's too bad we now have a wasted negative flag in the `big.Int`. Could you add to the commit message why that flag was not possible to use for this use case?
</blockquote></details>

Done.

---

*[decimal.go, line 202 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/29#-KerlS4Ud1xHh5q7B_cy:-KewA31SiJgPmicReX6G:b-896fix) ([raw file](https://github.com/cockroachdb/apd/blob/81ff665965ffbc37f95bf8190aea354799e6a529/decimal.go#L202)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: move this up one line
</blockquote></details>

Done.

---

*[decimal.go, line 365 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/29#-KerlZPA_zVLR7pTJixS:-KewB1QW58xzgBXByKJX:b-qyr8qu) ([raw file](https://github.com/cockroachdb/apd/blob/81ff665965ffbc37f95bf8190aea354799e6a529/decimal.go#L365)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This name implies that we're getting a reference to the `Decimal`'s `big.Int`. Instead, we're getting a deep copy. I'd either change the name to make this more clear or add a comment.
</blockquote></details>

Done. I've also changed it to take the target decimal so callers can allocate as desired.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/29)*

**Comment by mjibson** [comment]
I've also added some scary comments about not making Coeff negative OR ELSE.

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[context.go, line 112 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/29#-Kerj-CBQkQrvDdwzY2A:-KezCKBlVDDS-ncU1sqc:b-sjqss4) ([raw file](https://github.com/cockroachdb/apd/blob/81ff665965ffbc37f95bf8190aea354799e6a529/context.go#L112)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can we add a second commit that replaces all of the `d.Sign() == 0` uses everwhere with this new method?

---

*[context.go, line 124 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/29#-Keris7m4vvdQsYajfTR:-KezCXHaxBX4JjcwUzJA:b-omh1uq) ([raw file](https://github.com/cockroachdb/apd/blob/81ff665965ffbc37f95bf8190aea354799e6a529/context.go#L124)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

If there are we pass them. Until I can find a failing decTest I'm inclined to leave it as is because it'd require a medium-ish change to the rounding stuff since you can't compare function pointers for equality in go.
</blockquote></details>

Ok, then can this all just be `d.Negative = xn && yn` in the meantime?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/29#-:-KezCvDHPzqt6ImBUSfh:bnfp4nl)*

**Comment by mjibson** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[context.go, line 124 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/29#-Keris7m4vvdQsYajfTR:-KezJzPkviMXuOWDPfS0:b-896fix) ([raw file](https://github.com/cockroachdb/apd/blob/81ff665965ffbc37f95bf8190aea354799e6a529/context.go#L124)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Ok, then can this all just be `d.Negative = xn && yn` in the meantime?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/29)*

**Comment by mjibson** [comment]
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[context.go, line 112 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/29#-Kerj-CBQkQrvDdwzY2A:-KezLAz9G4eGiXYQWeaT:b-896fix) ([raw file](https://github.com/cockroachdb/apd/blob/81ff665965ffbc37f95bf8190aea354799e6a529/context.go#L112)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we add a second commit that replaces all of the `d.Sign() == 0` uses everwhere with this new method?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/29)*

**Pull request merged**
