### PR TITLE
Test cbrt

### PR DESCRIPTION
**Pull request by mjibson**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/apd/11)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[context.go, line 460 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/11#-KcGr6kGUGMhKVlPfMNm:-KcGr6kGUGMhKVlPfMNn:bfxgmwo) ([raw file](https://github.com/cockroachdb/apd/blob/5185518c92c17ae62d8b6b4a50e1a120973c0baa/context.go#L460)):*
> ```Go
> 
> 	// Loop until convergence.
> 	for loop := nc.newLoop("cbrt", z, c.Precision, 1); ; {
> ```

We may need `c.Precision+1` here (not sure if this is related to the new check below).

And sorry about the false, I was experimenting and I guess I accidentally left it there.

---

*[context.go, line 484 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/11#-KcGsPcgf_Do4JX5M8ej:-KcGsPcgf_Do4JX5M8ek:b-i4vuq1) ([raw file](https://github.com/cockroachdb/apd/blob/5185518c92c17ae62d8b6b4a50e1a120973c0baa/context.go#L484)):*
> ```Go
> 	}
> 
> 	// Cbrt has a flawed inexact determination. Due to how the loop termination
> ```

Could we check if we have an "exact" flag, and in that case multiply z by itself two times and see if it exactly equals the input?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/11)*

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[context.go, line 460 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/11#-KcGr6kGUGMhKVlPfMNm:-KcHSqk1-d4_A2CQi7d2:b-896fix) ([raw file](https://github.com/cockroachdb/apd/blob/5185518c92c17ae62d8b6b4a50e1a120973c0baa/context.go#L460)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We may need `c.Precision+1` here (not sure if this is related to the new check below).

And sorry about the false, I was experimenting and I guess I accidentally left it there.
</blockquote></details>

Done.

---

*[context.go, line 484 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/11#-KcGsPcgf_Do4JX5M8ej:-KcHSrTjlw1F20B5HSU6:bc9kyaf) ([raw file](https://github.com/cockroachdb/apd/blob/5185518c92c17ae62d8b6b4a50e1a120973c0baa/context.go#L484)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Could we check if we have an "exact" flag, and in that case multiply z by itself two times and see if it exactly equals the input?
</blockquote></details>

Inexact occurs during rounding when some non-zero digits are removed. Since this problem is caused by non-zero digits, we can't check for an exact flag because it's known to be inexact. For example `cbrt(1)` was getting something like `1.000000000000013`. After rounding this would set the Inexact flag.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/11)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[context.go, line 484 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/11#-KcGsPcgf_Do4JX5M8ej:-KcIPXdSb2TL-yb6koI_:bh7m911) ([raw file](https://github.com/cockroachdb/apd/blob/5185518c92c17ae62d8b6b4a50e1a120973c0baa/context.go#L484)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Inexact occurs during rounding when some non-zero digits are removed. Since this problem is caused by non-zero digits, we can't check for an exact flag because it's known to be inexact. For example `cbrt(1)` was getting something like `1.000000000000013`. After rounding this would set the Inexact flag.
</blockquote></details>

Ah, but then just because we were able to trim some zeroes after rounding, why do we decide that the result is exact? It could end in zeroes even if it isn't..

E.g. input 1.0001 with precision 5 should result in `1.0000` after rounding, which is correct for the precision (exact answer is ~ 1.00003333222), but not exact.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/11)*

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[context.go, line 484 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/11#-KcGsPcgf_Do4JX5M8ej:-KcJTz7ADd3k0zG2Nm79:b-mz2cps) ([raw file](https://github.com/cockroachdb/apd/blob/5185518c92c17ae62d8b6b4a50e1a120973c0baa/context.go#L484)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ah, but then just because we were able to trim some zeroes after rounding, why do we decide that the result is exact? It could end in zeroes even if it isn't..

E.g. input 1.0001 with precision 5 should result in `1.0000` after rounding, which is correct for the precision (exact answer is ~ 1.00003333222), but not exact.
</blockquote></details>

Yes, the situation you describe is exactly the problem this comment is describing. It is possible that this method needs the old loop code. Or maybe we need more tests like the one you list here and to figure out an algorithm that always works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/11)*

**Comment by RaduBerinde** [comment]
*[context.go, line 484 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/11#-KcGsPcgf_Do4JX5M8ej:-KcJWtvMZXgR_0MPtP71:b3bz5h8) ([raw file](https://github.com/cockroachdb/apd/blob/5185518c92c17ae62d8b6b4a50e1a120973c0baa/context.go#L484)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Yes, the situation you describe is exactly the problem this comment is describing. It is possible that this method needs the old loop code. Or maybe we need more tests like the one you list here and to figure out an algorithm that always works.
</blockquote></details>

I think with any loop termination code the problem above could happen.. So after we do the round and reduce, can't we multiply `d` with itself two times to see if it exactly matches x?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/11)*

**Comment by RaduBerinde** [comment]
*[context.go, line 477 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/11#-KcJZTMtucXpFd28JGx0:-KcJZTMtucXpFd28JGx1:b-we28r3) ([raw file](https://github.com/cockroachdb/apd/blob/5185518c92c17ae62d8b6b4a50e1a120973c0baa/context.go#L477)):*
> ```Go
> 			break
> 		}
> 		z0.Set(z)
> ```

These `z0.Set(z)` and `z.Set(z0)` are confusing. Can we replace all three by just a `z0.Set(z)` at the beginning of the loop?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/11)*

**Comment by mjibson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[context.go, line 477 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/11#-KcJZTMtucXpFd28JGx0:-KcJi7GVYCr6KesFaDVh:b-896fix) ([raw file](https://github.com/cockroachdb/apd/blob/5185518c92c17ae62d8b6b4a50e1a120973c0baa/context.go#L477)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

These `z0.Set(z)` and `z.Set(z0)` are confusing. Can we replace all three by just a `z0.Set(z)` at the beginning of the loop?
</blockquote></details>

Done.

---

*[context.go, line 484 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/11#-KcGsPcgf_Do4JX5M8ej:-KcJhRUR0_HLTveOp0Z_:b49smxf) ([raw file](https://github.com/cockroachdb/apd/blob/5185518c92c17ae62d8b6b4a50e1a120973c0baa/context.go#L484)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think with any loop termination code the problem above could happen.. So after we do the round and reduce, can't we multiply `d` with itself two times to see if it exactly matches x?
</blockquote></details>

Yes, this works. Much better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/11)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[context.go, line 484 at r1](https://reviewable.io:443/reviews/cockroachdb/apd/11#-KcGsPcgf_Do4JX5M8ej:-KcK-lxcUn83xwsVapk_:b-83sjoh) ([raw file](https://github.com/cockroachdb/apd/blob/5185518c92c17ae62d8b6b4a50e1a120973c0baa/context.go#L484)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Yes, this works. Much better.
</blockquote></details>

Nice!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/apd/11#-:-KcK-mfCYkS51r8nxl_H:bnfp4nl)*

**Pull request merged**
